Persist data to JSON by default
kylemcdonald/ethereum-nft-activity pull request #4
Opened 2021-03-15 03:35 UTC by pippinlee

Previously the script ran and had the user output to a `.tsv` file. This has been replaced with JSON to the `/output` direction.

The JSON format follows the following format:

```json
{
    "data": [
        {
            "name": "Async",
            "kind": "1",
            "address": "0x6c424c25e9f1fff9642cb5b7750b0db7312c29ad",
            "gas": 596562089,
            "transactions": 7410,
            "kgco2": 127053
        },
        {
            "name": "Async",
            "kind": "2",
            "address": "0xb6dae651468e9593e4581705a09c10a76ac1e0c8",
            "gas": 862954286,
            "transactions": 7304,
            "kgco2": 247305
        },
        ...
    ]
}
```

2021-03-23 00:33 UTC, kylemcdonald requested changes
Sorry! It looks like I "started a review" instead of just adding comments.

2021-03-23 00:33 UTC, kylemcdonald commented on cryptoart_footprint.py
> +contracts = load_contacts()
load_contacts should be load_contracts

2021-03-23 00:33 UTC, kylemcdonald commented on utils.py
> +        jsonFile.close()
for my code i always use `f` as the file variable (instead of `jsonFile`). `with open(...)` will automatically close the file when running out of scope, the `.close()` is unnecessary.

2021-03-23 00:33 UTC, kylemcdonald commented on utils.py
> +        return payload['etherscan-api-key']
better style to unindent the return here.

2021-03-23 00:33 UTC, kylemcdonald commented on utils.py
> +    result_filepath = f'./output/{current_datetime}.json'
if we save the output with an automatically generated filename (instead of printing to stdout and redirecting) then we should allow the filename to be set manually so we can use it later. this means adding an argument to this func, and also a command line argument to the script.

2021-03-23 04:08 UTC, kylemcdonald commented
sorry, some updates just now added conflicts. if you make the above changes then i can resolve the conflicts, if that helps 🙏

2021-03-26 01:32 UTC, pippinlee commented on utils.py
> +    result_filepath = f'./output/{current_datetime}.json'
I'm ok with this, but curious why we need to user to be able to name this file? Would a note in readme noting that this file is available suffice?

2021-03-31 17:06 UTC, merged